# Generated by Django 3.1 on 2023-05-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
