# Generated by Django 3.1 on 2023-05-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryboy_is_deliveryboy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
