# Generated by Django 3.1 on 2023-05-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_DeliveryBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('license_no', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deliveryboy', models.BooleanField(default=True)),
            ],
        ),
    ]
